import './assets/style/App.css'
import machine1 from './assets/icon/machinery/bag-conversion-line.webp'
import machine2 from './assets/icon/machinery/bobbin-cleaning-machine.webp'
import machine3 from './assets/icon/machinery/lamination-jpex.webp'
import machine4 from './assets/icon/machinery/looms.webp'
import machine5 from './assets/icon/machinery/tape-stretching-line.webp'
import machine6 from './assets/icon/machinery/manual-printing-machine.webp'
import machine7 from './assets/icon/machinery/hot-air-dryer.webp'
import machine8 from './assets/icon/machinery/gravimetric-dosing-mixer.webp'
import machine9 from './assets/icon/machinery/bale-press-machine.webp'
import machine10 from './assets/icon/machinery/manual-stitching.webp'
import machine11 from './assets/icon/machinery/flexographic.webp'
import machine12 from './assets/icon/machinery/weighing-scale.webp'





const Machinery = (props) => {



    return (<>
    <div className="machinery">
    <div style={{margin:'auto'}}><p style={{textAlign:'center'}}>Advanced Machinery for Plastic Bag Production at Microplast Polytex</p></div>
    <div style={{width:'90%',margin:'auto'}}><p>Discover Microplast Polytex's advanced machinery lineup, featuring bag conversion lines, flexographic printers, JP extrusion machines, tape stretching lines, and more. Our cutting-edge technology crafts premium products such as fertilizer sacks, rice bags, PP woven sacks, laminated gusseted bags, and PP fabrics, guaranteeing precision and efficiency throughout production for superior plastic bag solutions across industries.</p></div>
    
    <div style={{width:'90%',justifyContent:'end',display:'flex',backgroundColor:'#dedede',fontSize:'2vw',padding:'1rem',margin:'auto'}}><div className="productDataDiv" style={{width:'70%',margin:'auto',backgroundColor:'#cecece',height:'auto',borderRadius:'20px',paddingLeft:'2rem',overflowY:props.mobile?'auto':'hidden'}}> <p style={{fontFamily:'sans-serif',width:'92%',height:'80%',fontSize:props.mobile?'1rem':'1.3rem',textShadow:'1px 1px 1px #cecece'}}>Efficient Bag Conversion Line: Our state-of-the-art machinery transforms raw materials into high-quality bags with precision and speed, ensuring top-notch quality for your packaging needs</p></div><div style={{position:'relative'}}><p style={{width:'100%',position:'absolute',marginTop:'7vw',margin:'auto',textAlign:'center',top:'19vw',fontSize:props.mobile?'4vw':'2.5vw',color:'snow',textShadow:'2px 2px 2px black'}}>Bag Conversion Line</p><img src={machine1} style={{width:props.mobile?'22vw':'40vw',height:props.mobile?'22vw':'24vw',margin:'auto'}}></img></div></div>
    <div style={{width:'90%',justifyContent:'end',display:'flex',backgroundColor:'#dedede',fontSize:'2vw',padding:'1rem',margin:'auto'}}><div style={{position:'relative'}}><p style={{width:'100%',position:'absolute',marginTop:'7vw',margin:'auto',textAlign:'center',top:'24vw',fontSize:props.mobile?'4vw':'2.5vw',color:'snow',textShadow:'2px 2px 2px black'}}>Bag Conversion Line</p><img src={machine2} style={{width:props.mobile?'22vw':'30vw',height:props.mobile?'22vw':'23vw',margin:'auto'}}></img></div><div className="productDataDiv" style={{width:'70%',margin:'auto',backgroundColor:'#cecece',height:'auto',borderRadius:'20px',paddingLeft:'2rem',overflowY:props.mobile?'auto':'hidden'}}> <p style={{fontFamily:'sans-serif',width:'92%',height:'80%',fontSize:props.mobile?'1rem':'1.3rem',textShadow:'1px 1px 1px #cecece'}}>Efficient Bag Conversion Line: Our state-of-the-art machinery transforms raw materials into high-quality bags with precision and speed, ensuring top-notch quality for your packaging needs</p></div></div>
    <div style={{width:'90%',justifyContent:'end',display:'flex',backgroundColor:'#dedede',fontSize:'2vw',padding:'1rem',margin:'auto'}}><div className="productDataDiv" style={{width:'70%',margin:'auto',backgroundColor:'#cecece',height:'auto',borderRadius:'20px',paddingLeft:'2rem',overflowY:props.mobile?'auto':'hidden'}}> <p style={{fontFamily:'sans-serif',width:'92%',height:'80%',fontSize:props.mobile?'1rem':'1.3rem',textShadow:'1px 1px 1px #cecece'}}>Efficient Bag Conversion Line: Our state-of-the-art machinery transforms raw materials into high-quality bags with precision and speed, ensuring top-notch quality for your packaging needs</p></div><div style={{position:'relative'}}><p style={{width:'100%',position:'absolute',marginTop:'7vw',margin:'auto',textAlign:'center',top:'19vw',fontSize:props.mobile?'4vw':'2.5vw',color:'snow',textShadow:'2px 2px 2px black'}}>Bag Conversion Line</p><img src={machine3} style={{width:props.mobile?'22vw':'40vw',height:props.mobile?'22vw':'24vw',margin:'auto'}}></img></div></div>
    <div style={{width:'90%',justifyContent:'end',display:'flex',backgroundColor:'#dedede',fontSize:'2vw',padding:'1rem',margin:'auto'}}><div style={{position:'relative'}}><p style={{width:'100%',position:'absolute',marginTop:'7vw',margin:'auto',textAlign:'center',top:'24vw',fontSize:props.mobile?'4vw':'2.5vw',color:'snow',textShadow:'2px 2px 2px black'}}>Bag Conversion Line</p><img src={machine4} style={{width:props.mobile?'22vw':'30vw',height:props.mobile?'22vw':'23vw',margin:'auto'}}></img></div><div className="productDataDiv" style={{width:'70%',margin:'auto',backgroundColor:'#cecece',height:'auto',borderRadius:'20px',paddingLeft:'2rem',overflowY:props.mobile?'auto':'hidden'}}> <p style={{fontFamily:'sans-serif',width:'92%',height:'80%',fontSize:props.mobile?'1rem':'1.3rem',textShadow:'1px 1px 1px #cecece'}}>Efficient Bag Conversion Line: Our state-of-the-art machinery transforms raw materials into high-quality bags with precision and speed, ensuring top-notch quality for your packaging needs</p></div></div>
    <div style={{width:'90%',justifyContent:'end',display:'flex',backgroundColor:'#dedede',fontSize:'2vw',padding:'1rem',margin:'auto'}}><div className="productDataDiv" style={{width:'70%',margin:'auto',backgroundColor:'#cecece',height:'auto',borderRadius:'20px',paddingLeft:'2rem',overflowY:props.mobile?'auto':'hidden'}}> <p style={{fontFamily:'sans-serif',width:'92%',height:'80%',fontSize:props.mobile?'1rem':'1.3rem',textShadow:'1px 1px 1px #cecece'}}>Efficient Bag Conversion Line: Our state-of-the-art machinery transforms raw materials into high-quality bags with precision and speed, ensuring top-notch quality for your packaging needs</p></div><div style={{position:'relative'}}><p style={{width:'100%',position:'absolute',marginTop:'7vw',margin:'auto',textAlign:'center',top:'19vw',fontSize:props.mobile?'4vw':'2.5vw',color:'snow',textShadow:'2px 2px 2px black'}}>Bag Conversion Line</p><img src={machine5} style={{width:props.mobile?'22vw':'40vw',height:props.mobile?'22vw':'24vw',margin:'auto'}}></img></div></div>
    <div style={{width:'90%',justifyContent:'end',display:'flex',backgroundColor:'#dedede',fontSize:'2vw',padding:'1rem',margin:'auto'}}><div style={{position:'relative'}}><p style={{width:'100%',position:'absolute',marginTop:'7vw',margin:'auto',textAlign:'center',top:'24vw',fontSize:props.mobile?'4vw':'2.5vw',color:'snow',textShadow:'2px 2px 2px black'}}>Bag Conversion Line</p><img src={machine6} style={{width:props.mobile?'22vw':'30vw',height:props.mobile?'22vw':'23vw',margin:'auto'}}></img></div><div className="productDataDiv" style={{width:'70%',margin:'auto',backgroundColor:'#cecece',height:'auto',borderRadius:'20px',paddingLeft:'2rem',overflowY:props.mobile?'auto':'hidden'}}> <p style={{fontFamily:'sans-serif',width:'92%',height:'80%',fontSize:props.mobile?'1rem':'1.3rem',textShadow:'1px 1px 1px #cecece'}}>Efficient Bag Conversion Line: Our state-of-the-art machinery transforms raw materials into high-quality bags with precision and speed, ensuring top-notch quality for your packaging needs</p></div></div>
    <div style={{width:'90%',justifyContent:'end',display:'flex',backgroundColor:'#dedede',fontSize:'2vw',padding:'1rem',margin:'auto'}}><div className="productDataDiv" style={{width:'70%',margin:'auto',backgroundColor:'#cecece',height:'auto',borderRadius:'20px',paddingLeft:'2rem',overflowY:props.mobile?'auto':'hidden'}}> <p style={{fontFamily:'sans-serif',width:'92%',height:'80%',fontSize:props.mobile?'1rem':'1.3rem',textShadow:'1px 1px 1px #cecece'}}>Efficient Bag Conversion Line: Our state-of-the-art machinery transforms raw materials into high-quality bags with precision and speed, ensuring top-notch quality for your packaging needs</p></div><div style={{position:'relative'}}><p style={{width:'100%',position:'absolute',marginTop:'7vw',margin:'auto',textAlign:'center',top:'19vw',fontSize:props.mobile?'4vw':'2.5vw',color:'snow',textShadow:'2px 2px 2px black'}}>Bag Conversion Line</p><img src={machine7} style={{width:props.mobile?'22vw':'40vw',height:props.mobile?'22vw':'24vw',margin:'auto'}}></img></div></div>
    <div style={{width:'90%',justifyContent:'end',display:'flex',backgroundColor:'#dedede',fontSize:'2vw',padding:'1rem',margin:'auto'}}><div style={{position:'relative'}}><p style={{width:'100%',position:'absolute',marginTop:'7vw',margin:'auto',textAlign:'center',top:'24vw',fontSize:props.mobile?'4vw':'2.5vw',color:'snow',textShadow:'2px 2px 2px black'}}>Bag Conversion Line</p><img src={machine8} style={{width:props.mobile?'22vw':'30vw',height:props.mobile?'22vw':'23vw',margin:'auto'}}></img></div><div className="productDataDiv" style={{width:'70%',margin:'auto',backgroundColor:'#cecece',height:'auto',borderRadius:'20px',paddingLeft:'2rem',overflowY:props.mobile?'auto':'hidden'}}> <p style={{fontFamily:'sans-serif',width:'92%',height:'80%',fontSize:props.mobile?'1rem':'1.3rem',textShadow:'1px 1px 1px #cecece'}}>Efficient Bag Conversion Line: Our state-of-the-art machinery transforms raw materials into high-quality bags with precision and speed, ensuring top-notch quality for your packaging needs</p></div></div>
    <div style={{width:'90%',justifyContent:'end',display:'flex',backgroundColor:'#dedede',fontSize:'2vw',padding:'1rem',margin:'auto'}}><div className="productDataDiv" style={{width:'70%',margin:'auto',backgroundColor:'#cecece',height:'auto',borderRadius:'20px',paddingLeft:'2rem',overflowY:props.mobile?'auto':'hidden'}}> <p style={{fontFamily:'sans-serif',width:'92%',height:'80%',fontSize:props.mobile?'1rem':'1.3rem',textShadow:'1px 1px 1px #cecece'}}>Efficient Bag Conversion Line: Our state-of-the-art machinery transforms raw materials into high-quality bags with precision and speed, ensuring top-notch quality for your packaging needs</p></div><div style={{position:'relative'}}><p style={{width:'100%',position:'absolute',marginTop:'7vw',margin:'auto',textAlign:'center',top:'19vw',fontSize:props.mobile?'4vw':'2.5vw',color:'snow',textShadow:'2px 2px 2px black'}}>Bag Conversion Line</p><img src={machine9} style={{width:props.mobile?'22vw':'40vw',height:props.mobile?'22vw':'24vw',margin:'auto'}}></img></div></div>
    <div style={{width:'90%',justifyContent:'end',display:'flex',backgroundColor:'#dedede',fontSize:'2vw',padding:'1rem',margin:'auto'}}><div style={{position:'relative'}}><p style={{width:'100%',position:'absolute',marginTop:'7vw',margin:'auto',textAlign:'center',top:'24vw',fontSize:props.mobile?'4vw':'2.5vw',color:'snow',textShadow:'2px 2px 2px black'}}>Bag Conversion Line</p><img src={machine10} style={{width:props.mobile?'22vw':'30vw',height:props.mobile?'22vw':'23vw',margin:'auto'}}></img></div><div className="productDataDiv" style={{width:'70%',margin:'auto',backgroundColor:'#cecece',height:'auto',borderRadius:'20px',paddingLeft:'2rem',overflowY:props.mobile?'auto':'hidden'}}> <p style={{fontFamily:'sans-serif',width:'92%',height:'80%',fontSize:props.mobile?'1rem':'1.3rem',textShadow:'1px 1px 1px #cecece'}}>Efficient Bag Conversion Line: Our state-of-the-art machinery transforms raw materials into high-quality bags with precision and speed, ensuring top-notch quality for your packaging needs</p></div></div>
    <div style={{width:'90%',justifyContent:'end',display:'flex',backgroundColor:'#dedede',fontSize:'2vw',padding:'1rem',margin:'auto'}}><div className="productDataDiv" style={{width:'70%',margin:'auto',backgroundColor:'#cecece',height:'auto',borderRadius:'20px',paddingLeft:'2rem',overflowY:props.mobile?'auto':'hidden'}}> <p style={{fontFamily:'sans-serif',width:'92%',height:'80%',fontSize:props.mobile?'1rem':'1.3rem',textShadow:'1px 1px 1px #cecece'}}>Efficient Bag Conversion Line: Our state-of-the-art machinery transforms raw materials into high-quality bags with precision and speed, ensuring top-notch quality for your packaging needs</p></div><div style={{position:'relative'}}><p style={{width:'100%',position:'absolute',marginTop:'7vw',margin:'auto',textAlign:'center',top:'19vw',fontSize:props.mobile?'4vw':'2.5vw',color:'snow',textShadow:'2px 2px 2px black'}}>Bag Conversion Line</p><img src={machine11} style={{width:props.mobile?'22vw':'40vw',height:props.mobile?'22vw':'24vw',margin:'auto'}}></img></div></div>
    <div style={{width:'90%',justifyContent:'end',display:'flex',backgroundColor:'#dedede',fontSize:'2vw',padding:'1rem',margin:'auto'}}><div style={{position:'relative'}}><p style={{width:'100%',position:'absolute',marginTop:'7vw',margin:'auto',textAlign:'center',top:'24vw',fontSize:props.mobile?'4vw':'2.5vw',color:'snow',textShadow:'2px 2px 2px black'}}>Bag Conversion Line</p><img src={machine12} style={{width:props.mobile?'22vw':'30vw',height:props.mobile?'22vw':'23vw',margin:'auto'}}></img></div><div className="productDataDiv" style={{width:'70%',margin:'auto',backgroundColor:'#cecece',height:'auto',borderRadius:'20px',paddingLeft:'2rem',overflowY:props.mobile?'auto':'hidden'}}> <p style={{fontFamily:'sans-serif',width:'92%',height:'80%',fontSize:props.mobile?'1rem':'1.3rem',textShadow:'1px 1px 1px #cecece'}}>Efficient Bag Conversion Line: Our state-of-the-art machinery transforms raw materials into high-quality bags with precision and speed, ensuring top-notch quality for your packaging needs</p></div></div>
    
    <div style={{margin:'auto'}}><p style={{textAlign:'center'}}>Testing Tools</p></div>
    <div style={{width:'90%',justifyContent:'end',display:'flex',backgroundColor:'#dedede',fontSize:'2vw',padding:'1rem',margin:'auto'}}><div className="productDataDiv" style={{width:'70%',margin:'auto',backgroundColor:'#cecece',height:'auto',borderRadius:'20px',paddingLeft:'2rem',overflowY:props.mobile?'auto':'hidden'}}> <p style={{fontFamily:'sans-serif',width:'92%',height:'80%',fontSize:props.mobile?'1rem':'1.3rem',textShadow:'1px 1px 1px #cecece'}}>Efficient Bag Conversion Line: Our state-of-the-art machinery transforms raw materials into high-quality bags with precision and speed, ensuring top-notch quality for your packaging needs</p></div><div style={{position:'relative'}}><p style={{width:'100%',position:'absolute',marginTop:'7vw',margin:'auto',textAlign:'center',top:'19vw',fontSize:props.mobile?'4vw':'2.5vw',color:'snow',textShadow:'2px 2px 2px black'}}>Bag Conversion Line</p><img src={machine9} style={{width:props.mobile?'22vw':'40vw',height:props.mobile?'22vw':'24vw',margin:'auto'}}></img></div></div>
    <div style={{width:'90%',justifyContent:'end',display:'flex',backgroundColor:'#dedede',fontSize:'2vw',padding:'1rem',margin:'auto'}}><div style={{position:'relative'}}><p style={{width:'100%',position:'absolute',marginTop:'7vw',margin:'auto',textAlign:'center',top:'24vw',fontSize:props.mobile?'4vw':'2.5vw',color:'snow',textShadow:'2px 2px 2px black'}}>Bag Conversion Line</p><img src={machine10} style={{width:props.mobile?'22vw':'30vw',height:props.mobile?'22vw':'23vw',margin:'auto'}}></img></div><div className="productDataDiv" style={{width:'70%',margin:'auto',backgroundColor:'#cecece',height:'auto',borderRadius:'20px',paddingLeft:'2rem',overflowY:props.mobile?'auto':'hidden'}}> <p style={{fontFamily:'sans-serif',width:'92%',height:'80%',fontSize:props.mobile?'1rem':'1.3rem',textShadow:'1px 1px 1px #cecece'}}>Efficient Bag Conversion Line: Our state-of-the-art machinery transforms raw materials into high-quality bags with precision and speed, ensuring top-notch quality for your packaging needs</p></div></div>
    <div style={{width:'90%',justifyContent:'end',display:'flex',backgroundColor:'#dedede',fontSize:'2vw',padding:'1rem',margin:'auto'}}><div className="productDataDiv" style={{width:'70%',margin:'auto',backgroundColor:'#cecece',height:'auto',borderRadius:'20px',paddingLeft:'2rem',overflowY:props.mobile?'auto':'hidden'}}> <p style={{fontFamily:'sans-serif',width:'92%',height:'80%',fontSize:props.mobile?'1rem':'1.3rem',textShadow:'1px 1px 1px #cecece'}}>Efficient Bag Conversion Line: Our state-of-the-art machinery transforms raw materials into high-quality bags with precision and speed, ensuring top-notch quality for your packaging needs</p></div><div style={{position:'relative'}}><p style={{width:'100%',position:'absolute',marginTop:'7vw',margin:'auto',textAlign:'center',top:'19vw',fontSize:props.mobile?'4vw':'2.5vw',color:'snow',textShadow:'2px 2px 2px black'}}>Bag Conversion Line</p><img src={machine11} style={{width:props.mobile?'22vw':'40vw',height:props.mobile?'22vw':'24vw',margin:'auto'}}></img></div></div>
    <div style={{width:'90%',justifyContent:'end',display:'flex',backgroundColor:'#dedede',fontSize:'2vw',padding:'1rem',margin:'auto'}}><div style={{position:'relative'}}><p style={{width:'100%',position:'absolute',marginTop:'7vw',margin:'auto',textAlign:'center',top:'24vw',fontSize:props.mobile?'4vw':'2.5vw',color:'snow',textShadow:'2px 2px 2px black'}}>Bag Conversion Line</p><img src={machine12} style={{width:props.mobile?'22vw':'30vw',height:props.mobile?'22vw':'23vw',margin:'auto'}}></img></div><div className="productDataDiv" style={{width:'70%',margin:'auto',backgroundColor:'#cecece',height:'auto',borderRadius:'20px',paddingLeft:'2rem',overflowY:props.mobile?'auto':'hidden'}}> <p style={{fontFamily:'sans-serif',width:'92%',height:'80%',fontSize:props.mobile?'1rem':'1.3rem',textShadow:'1px 1px 1px #cecece'}}>Efficient Bag Conversion Line: Our state-of-the-art machinery transforms raw materials into high-quality bags with precision and speed, ensuring top-notch quality for your packaging needs</p></div></div>
   
    
    </div>
    
    </>)
}
export default Machinery