const Quality = () => {
    return (<>
        <div style={{margin:'auto'}}><p style={{textAlign:'center'}}>Quality Assurance</p></div>
        <div style={{width:'90%',margin:'auto'}}>
        <p>Our fabric production process stands as a paragon of excellence, meticulously governed by stringent quality control procedures. Through these rigorous checks, we unfailingly present our discerning customers with products that transcend technical expectations, boasting an astonishing defect rate of less than 1%. The very essence of our polypropylene fabric lies in its hydrophobic nature, steadfastly repelling moisture and whisking away perspiration from the skin. Our manufacturing prowess, underpinned by state-of-the-art machinery and a customer-centric approach, empowers us to craft fabrics that effortlessly meet and exceed the exacting demands of our esteemed clientele. <br></br>Quality at Microplast is not a mere coincidence; it emerges as a harmonious symphony of unwavering dedication, astute guidance, and expert execution throughout our entire production journey. We meticulously adhere to a meticulously defined quality management system, starting from the meticulous procurement of raw materials and culminating in the flawless dispatch of our products. Our chosen materials are fortified with UV stabilizers, rendering them impervious to the ravages of ultraviolet rays. At every stage of production, our seasoned quality control professionals wield their expertise to orchestrate impeccable task execution.<br></br>Bolstered by cutting-edge machinery, our production unit is an epicenter of continuous innovation and refinement. We harness the capabilities of cutting-edge sewing machines, ensuring both safety and enduring durability in every stitch. Impeccable printing quality and unmatched clarity are achieved through the use of indelible ink. Only after an uncompromising quest for perfection, unyielding testing, and painstaking inspection, is a batch of our products deemed fit for delivery.<br></br>Yet, our commitment to quality extends far beyond the confines of our products; it encompasses our services as well. We pledge to our clients prompt, world-spanning delivery services that are as impeccable as the products themselves. At Microplast, quality is not a destination; it is an unwavering journey towards excellence that we undertake, ensuring that our customers receive nothing but the very best, every time.</p>
            
        </div>
    
        </>)
}
export default Quality